micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attepts: 10
  channels:
    key-manager:
      address: "localhost:50051"
      plaintext: true
      max-retry-attepts: 5